#   conda env create -f environment.yml
name: HiC-Pro_v3.1.0
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python
  - conda-forge::scipy
  - conda-forge::numpy
  - bioconda::iced
  - bioconda::bx-python
  - bioconda::pysam
  - bioconda::cooler

  - conda-forge::r-base
  - conda-forge::r-ggplot2
  - conda-forge::r-rcolorbrewer
  - conda-forge::r-gridbase
  
  - conda-forge::tbb
  - bioconda::bowtie2
  - bioconda::samtools
  - bioconda::multiqc
